nvim-neotest/neotest

README.md

Adds a reference to the `neotest-go` adapter
Relates to #6

docs(README): add link to neotest-go adapter

---

lua/neotest/lib/positions/init.lua
lua/neotest/types/tree.lua
tests/unit/lib/positions/init_spec.lua

While debugging #30, I discovered that the reason tests weren't updating on save was because the root tree was a `type = 'file'`, and merging `type = 'file'` _into_ `type = 'file'` did not do anything.
This PR adds the following capabilities:
* Merging file into file works as expected
* Merging a _new_ file into a dir works (previously produced error)
* Merging two dirs with no common root joins them both under a new tree based at the common ancestor
I've added tests for everything, but let me know if there are other cases that you think should be covered.

Enable position merging for more cases

---

doc/neotest.txt
lua/neotest/client/init.lua
lua/neotest/config/init.lua
tests/unit/client/init_spec.lua

Intended to address #13
Relatively straightforward: adds a config option that, when disabled, doesn't call `_update_positions` on directories. Files still get populated in the summary on `BufOpen`/`BufWritePost`, and I also added some logic to scan the files that vim opens on start.
New functionality
- Set `discovery.enabled = false`
- Open a test file in a directory with multiple test files
- Observe that the test summary only displays the currently-open file
Nothing broke
- Set `discovery.enabled = true`
- Open a test file in a directory with multiple test files
- Observe that the test summary displays all discoverable tests, as per usual
Per-directory configuration would still be a great addition. Another feature that could be cool is some test adapters are capable of running tests on …

Allow disabling directory crawling for tests

---

doc/neotest.txt
lua/neotest/async.lua
lua/neotest/client/init.lua
lua/neotest/client/runner.lua
lua/neotest/client/state/init.lua
lua/neotest/client/strategies/dap/init.lua
lua/neotest/client/strategies/init.lua
lua/neotest/client/strategies/integrated/init.lua
lua/neotest/consumers/output.lua
lua/neotest/lib/file/init.lua
lua/neotest/types/fanout_accum.lua
lua/neotest/types/init.lua
tests/unit/client/init_spec.lua
tests/unit/client/strategies/integrated_spec.lua
tests/unit/lib/files/init_spec.lua

Related discussion: https://github.com/nvim-neotest/neotest/discussions/48
This change allows for streaming results in 2 ways:
1. For adapters that break up the tree so run multiple processes, results for each process can be streamed so users can see it as separate processes rather than looking like one.
2. Adapters can provide a `stream` argument in the spec returned by `build_spec` which takes an async iterator over the lines of output data from the process and returns an iterator of results tables
The stream argument can look something like this
```lua
stream = function(data)
return function()
local lines = data()
local results = {}
for _, line in ipairs(lines) do
local result = vim.json.decode(line, { luanil = { object = true } })
results[result.id] = result.result
end
return results …
```

feat: streamed results

---

doc/neotest.txt
lua/neotest/client/runner.lua
lua/neotest/config/init.lua

I've written [a custom neotest strategy](https://github.com/stevearc/overseer.nvim/blob/master/lua/neotest/client/strategies/overseer.lua) and I'd like to use it by default. I tested both by setting the `default_strategy` and leaving it empty in the call to `setup()`, and both cases work as expected.

feat: add config option to specify default strategy

---

doc/neotest.txt
lua/neotest/consumers/run.lua

Following up on #76, it turns out I actually _would_ really like this helper function to be exposed.

refactor: expose neotest.run.get_tree_from_args

---

lua/neotest/consumers/diagnostic.lua

Small bug introduced in 4fdce02df7046b7f8be8b112377d8c65593f2553 that broke the diagnostics consumer. Fix is straightforward

fix: crash in diagnostics consumer

---

ftplugin/neotest-summary.vim
lua/neotest/consumers/summary/init.lua

The standard Vim way of setting filetype-specific settings is to add them to an `ftplugin/my-filetype.{vim,lua}` file (`:h ftplugin`), but this does not in Neotest work with window-specific options like `'spell'`. The solution was to delay setting the file type until after the window exists. While at it I also moved the default settings to a dedicated file to save some lines of code and I added the `nospell` setting because I think we should have that as a default.
Personally I would remove the `norelativenumber` setting from the defaults because we already have `nonumber` in the defaults. If users want to turn numbers back on we should not be forcing absolute numbers on them. What is your opinion?

[RFC] Delay setting file type of summary buffers

---

README.md

Adds docs for [neotest-scala ](https://github.com/stevanmilic/neotest-scala)adapter.
Here's a short video showing the adapter in action:
https://user-images.githubusercontent.com/6879030/191082489-fc8f9d2a-07f1-41de-ba2c-1efd81efb059.mov

docs(README): add neotest-scala

---

doc/neotest.txt
lua/neotest/consumers/output.lua
lua/neotest/consumers/run.lua

Running `:lua require('neotest').output.open({ last_run = true })` will open output of last test run. 
I created this to support the workflow:
- Run a test with `:lua require("neotest").run.run()`.
- Edit implementation in a split, next to the test file.
- Run `:lua require("neotest").run.run_last()` to run last test while still in non-test buffer.
- Run `:lua require('neotest').output.open({ last_run = true })` to check it's output still in the non-test buffer.
Should not be feature creep, so if there's a better way to support this workflow, let me know!

feat(output): open output for last test run

---

lua/neotest/consumers/summary/canvas.lua

These, predictably, perform the given action across the tests in the selected visual range.
This commits adds a summary.map_in_visual config option: actions listed there will have their configured keys mapped in visual mode.
Fixes: #143

feat(summary): map mark/run/stop keybindings in visual mode

---

lua/neotest/adapters/interface.lua

Thought this might help future devs more easily discover the joy of the `filter_dir` interface you showed me in #154. :)

Add return annotation for `filter_dir` interface

---

lua/neotest/consumers/summary/init.lua

This enables API consumers (such as user config) to query for marked tests, enabling them to change their behaviour when there are.

feat(summary): add marked function to API

---

lua/neotest/adapters/init.lua

`vim.api.nvim_buf_get_name()` will throw an error if run on an unloaded buffer. I'm using `noice.nvim` which I think creates some unloaded buffers.
This PR adds a check to ensure the buffer is loaded before trying to get the name.

fix: run fails if there are unloaded buffers

---

lua/neotest/consumers/summary/canvas.lua

This can provide more information or description about what each key
is mapped to in neotest summary buffers, for `:map <buffer>` or
any other plugins that can show keymap info.
For instance:
```
:map <buffer>
n  <CR>        *@<Lua 2029: .../neotest/lua/neotest/consumers/summary/canvas.lua:133>
expand (Neotest Summary)
n  D           *@<Lua 1398: .../neotest/lua/neotest/consumers/summary/canvas.lua:133>
debug_marked (Neotest Summary)
...
```

feat(summary): Add descriptions for buffer-local keymaps in summary

---

lua/neotest/lib/ui/float.lua

This would be a better solution for #136; when a neotest output window
is moved (initialized as a floating window) as normal windows,
the window should be no longer automatically closed.

fix(float): Do not auto-close window if it is no longer a floating win

---

lua/neotest/client/events/init.lua
lua/neotest/client/init.lua
lua/neotest/consumers/run.lua
lua/neotest/consumers/summary/init.lua
lua/neotest/consumers/summary/summary.lua
lua/neotest/types/init.lua
tests/unit/client/init_spec.lua

BREAKING CHANGE: Removes the `has_started` and `ensure_started` client methods
See #157

feat: started and starting events

---

lua/neotest/lib/subprocess.lua

Running MacOS Ventura 13.1 on an M1 Chip.
Trying to run any command with Neotest results in the following error message:
```
E5108: Error executing lua ...ck/packer/start/plenary.nvim/lua/plenary/async/async.lua:18: The coroutine failed with this message: Vim:Failed to start server: address already in use
stack traceback:
[C]: in function 'error'
...ck/packer/start/plenary.nvim/lua/plenary/async/async.lua:18: in function 'callback_or_next'
...ck/packer/start/plenary.nvim/lua/plenary/async/async.lua:45: in function 'step'
...ck/packer/start/plenary.nvim/lua/plenary/async/async.lua:48: in function 'execute'
...ck/packer/start/plenary.nvim/lua/plenary/async/async.lua:108: in function 'run'
.../pack/packer/start/neotest/lua/neotest/consumers/run.lua:67: in function 'run'
[string ":lua"]:1: in …
```

fix: Let Neovim Pick Random Port

---

lua/neotest/client/init.lua

I'm seeing an error when setting `discovery.enabled = false`. I have an adapter that does not have any valid tests discovered, and thus has no root position in the state. This causes the assert here to always fail, which means that I see an error on every `BufAdd` and `BufWritePost`. The repro is as follows:
1. Open a file in a different language from the test adapter
2. Open the summary pane `require("neotest").summary.toggle()`
3. Open any new buffer `:enew`
Observe error
The fix I put in was to silently ignore the adapter if there is no root. I think this is fine (as that is a valid state), but let me know if that is not the case.

fix: don't error if adapter has no root position

---

doc/neotest.txt
lua/neotest/client/init.lua
lua/neotest/client/runner.lua
lua/neotest/consumers/diagnostic.lua
lua/neotest/consumers/jump.lua
lua/neotest/consumers/output.lua
lua/neotest/consumers/status.lua
lua/neotest/consumers/summary/component.lua
lua/neotest/types/tree.lua

Not all tests have a unique range which applies to them.  For example, in pytest, a test function can be parametrized to produce multiple different test instances for the same range.  neotest currently assumes that any cursor position in a file maps to a single test, and selects the deepest-nested such test: this results in the last test instance for a test function being focused, instead of the whole test: the only way to run other (or all) instances is via the summary view.
This commit changes neotest's behaviour, by introducing support for "child" test positions: these are simply test positions with `range` set to `nil`.  This commit updates all[0] direct accesses of `range` on positions with calls to `Tree:closest_value_for("range")`: this will traverse up the parents of a node, …

feat(neotest): support range-less "child" tests

---

lua/neotest/client/runner.lua

This will solve error:
```
Error executing luv callback:                                                                                   
...ck/packer/start/plenary.nvim/lua/plenary/async/async.lua:18: The coroutine failed with this message: ...ck/pa
cker/start/plenary.nvim/lua/plenary/async/async.lua:18: The coroutine failed with this message: ...ck/packer/sta
rt/plenary.nvim/lua/plenary/async/async.lua:18: The coroutine failed with this message: ...ck/packer/start/plena
ry.nvim/lua/plenary/async/async.lua:18: The coroutine failed with this message: .../pack/packer/start/neotest/lu
a/neotest/client/runner.lua:267: attempt to index a nil value                                                   
stack traceback:      
```

fix: check for not available test before trying getting results

---

lua/neotest/consumers/quickfix.lua

otherwise we wouldn't remove obsolete errors after fixing a test.

quickfix: always set QF list after a test run

---

lua/neotest/lib/treesitter/init.lua

See https://github.com/neovim/neovim/pull/22761
Couldn't run the tests. Getting an error about plenary:
```
E492: Not an editor command: PlenaryBustedDirectory tests/ {minimal_init = 'tests/init.vim'}
```

fix(deprecation): Use query.parse to avoid deprecation warning

---

lua/neotest/consumers/diagnostic.lua

If the column is 0, but the code doesn't start on the first column, which isn't what we want. The cursor will be placed to the left of the actual definition.

Enhance diagnotic column position

---

lua/neotest/client/strategies/dap/init.lua

Fixed a bug where a zombie handler was raising error when consequently running debug test in the same neovim session.
- Go to a test
- Run `neotest.run.run({strategy='dap'})` two times in the same neovim session
```sh
Error executing vim.schedule lua callback: .../neotest/lua/nio/control.lua:88: Future already set
stack traceback:
[C]: in function 'error'
.../neotest/lua/nio/control.lua:88: in function 'set'
.../neotest/client/strategies/dap/init.lua:49: in function 'c'
.../nvim-dap/lua/dap/session.lua:982: in function <.../nvim-dap/lua/dap/session.lua:970>
```
Because the `event_exited` event handler was not cleaned up, it was called twice unintentionally in the next run. Cleaning up the event handler was missing after dap execution.

fix(client): dap handler cleanup bug

---

lua/neotest/client/strategies/integrated/init.lua
lua/neotest/consumers/output.lua

This fixes issues with autocmds such as `WinLeave` not firing,
presumable due to the fact that the floating window gets disposed of
when its buffer is deleted. This breaks plugins such as
[tint.nvim][tint.nvim] who rely on `WinLeave` to function properly.
[tint.nvim]: https://github.com/levouh/tint.nvim/issues/38

fix: utilize bufhidden=wipe instead of forcibly deleting buffer

---

lua/neotest/client/strategies/integrated/init.lua

I've ran into a bug that prevents users to attach to a running test more than once. To replicate, run a long running test, attach to it, close the floating window, and try to attach to the test again. 
You should currently get an error message like so:
<details>
E5108: Error executing lua ...e/janmo/.local/share/nvim/lazy/neotest/lua/nio/tasks.lua:95: Async task failed without callback: The coroutine failed with this message: 
...cal/share/nvim/lazy/neotest/lua/neotest/lib/ui/float.lua:104: Invalid buffer id: 3
stack traceback:
[C]: in function 'nvim_open_win'
...cal/share/nvim/lazy/neotest/lua/neotest/lib/ui/float.lua:104: in function 'open'
...eotest/lua/neotest/client/strategies/integrated/init.lua:88: in function 'attach'
...nvim/lazy/neotest/lua/neotest/client/strategies/init.lua:85: …

Check for buffer existence on attach function

---

plugin/neotest.lua

Add initial implementation of the `:Neotest` command with completion support.
Instead of adding a lot of command, it's cleaner to have a single one.
The structure will be like this:
`:Neotest [cmd] [subcmd] [...]`
Most of the functionality that I could find are exposed with this command.
---
- Resolve https://github.com/nvim-neotest/neotest/issues/241
- Resolve https://github.com/nvim-neotest/neotest/issues/252
- https://github.com/nvim-neotest/neotest/discussions/227

feat: add command ':Neotest'

---

lua/neotest/consumers/diagnostic.lua

After closing the buf, the `mark[1]` becomes `nil`, so we can't just `mark[1] + 1`

Fix bug caused by buf closing

---

lua/neotest/client/init.lua

I'm using neotest-dotnet while also using vim-fugitive and I've noticed that it breaks when I open a fugitive file (i.e. I'll open a diff on the current file with `:Gdiffsplit`). This is because the fugitive diff file (starting with `fugitive:///...`) doesn't exist on disk and neotest-dotnet attempts to load it while being asked if it's a test file.
Some steps to reproduce:
1. Run tests in a test file using neotest-dotnet
2. `:Gdiffsplit`
You'll see this:
```
Error executing luv callback:                                                                                                                                                                                     
/Users/tim/.local/share/nvim/lazy/neotest/lua/nio/tasks.lua:95: Async task failed without callback: The coroutine failed …
```

Check if file exists before calling is_test_file

---

.github/workflows/workflow.yaml
README.md
lua/neotest/lib/subprocess.lua
lua/neotest/lib/treesitter/init.lua
tests/minimal_init.lua

Nvim-treesitter's 1.0 rewrite will remove all utilities/functionality it provides since vim.treesitter pretty much covers it all now,  you can read more in the *main* branch's readme (default is master)

refactor!: remove nvim-treesitter dependency

---

doc/neotest.txt
lua/neotest/consumers/output_panel/init.lua
plugin/neotest.lua

Often while re-running tests it's hard to see what is output of the current run and output of the last run.
By manually wiring clear() into my bindings I can choose when to clear and when not.

feat: add output_panel.clear()

---

lua/neotest/consumers/status.lua

This fixes #305, by ensuring that rangeless tests will not have markers written at all, avoiding overwriting their parent's mark.
This does introduce another, less significant, issue: the marker for a test will always indicate the result of the last time that the parent test was explicitly executed, including being absent if the parent test has never been specifically requested.  (Currently, this likely only occurs when using the summary window, so users can reference that for more precise result info.  This could become a more annoying issue with, for example, a "run all failed tests" command in future which might bypass parent test execution.)

status: only place marks for tests with their own range

---

README.md

Adding [neotest-gtest](https://github.com/alfaix/neotest-gtest) to the list as it's now more-or-less functional.
Also wanted to mention - I wrote integration tests while working on the plugin, they allow writing tests like [this](https://github.com/alfaix/neotest-gtest/blob/main/tests/integration/plugin_spec.lua#L27) from files like [this](https://github.com/alfaix/neotest-gtest/blob/main/tests/integration/cpp/src/test_one.cpp#L13). Would it make sense to contribute the testing tools to this plugin? Of course, `configure_executable` and things like that don't make sense for other adapters, but I think the general "write test project" -> "ensure it's running" flow would help with testing.

doc(readme): add neotest-gtest

---

.github/workflows/luarocks-release.yaml

This fixes the luarocks release workflow:
- Removes treesitter from the dependencies
- Makes sure the workflow can be triggered by GitHub releases

ci: fix luarocks-release workflow

---

README.md

Tests might not be found if treesitter is not added as a direct dependency to neotest. Most distros fixed this themselves, but the documentation in neotest would be an improvement.

Update README.md to include treesitter dependency

---

README.md

Adds [neotest-bash](https://github.com/rcasia/neotest-bash) to README.

doc: add neotest-bash adapter

---

lua/neotest/lib/subprocess.lua

Hi! 👋
I've been having a bug for a while which happened seemingly randomly: sometimes when toggling the test summary window, Neovim would freeze completely, forcing a kill + restart of the process.
Steps were the following:
- `nvim`
- `:lua require('neotest').summary.toggle()`
- freeze happens
I found the hanging line with some trial and error, `subprocess.lua:41` which tries to load neotest in the nvim subprocess and blocks until it gets a response. The fix I found is to spawn the nvim subprocess with swap files disabled.
I have the `Shatur/neovim-session-manager` plugin installed, and it is configured (by default) to open the last opened session when running `nvim` without providing a file/dir argument. At some point after toggling the summary window, the nvim subprocess is spawned with …

fix: opening summary window freezes when subprocess finds swap file

---

lua/neotest/client/runner.lua
lua/neotest/client/strategies/dap/init.lua
lua/neotest/types/init.lua

Whenever the debug mapping is used inside the summary window and a breakpoint is hit, nvim-dap hijacks the summary window to focus the breakpoint.
- Set config option `switchbuf = 'uselast'` in nvim-dap (default)
- Open test file
- Set a breakpoint in test
- Open + move to summary window
- Use debug mapping `d` on test
The window containing the test buffer should be used to focus the breakpoint.
`nvim-dap` has the `switchbuf` config option to to control how a breakpoint is jumped to, the default is `uselast` and it probably makes the most sense as a default for neotest too. It works like this: when `dap.run()` is executed, if the current buffer is a normal buffer or `dap.run()` is not provided with a different `filetype` than the current buffer, then the current window is used to focus …

fix: nvim-dap hijacks summary window when using the debug mapping

---

lua/neotest/client/strategies/dap/init.lua

Currently, it is not possible to stop a test running through the debug strategy (by calling `require("neotest").run.stop()`.
This results in the following error:
```
E5108: Error executing lua: ...quitlox/.local/share/nvim/lazy/neotest/lua/nio/tasks.lua:95: Async task failed without callback: Th
e coroutine failed with this message:                                                                                             
...nvim/lazy/neotest/lua/neotest/client/strategies/init.lua:66: attempt to call field 'stop' (a nil value)                        
stack traceback:                                                                                                                  
...nvim/lazy/neotest/lua/neotest/client/strategies/init.lua: in function 'stop' …
```

fix: allow terminating tests run through dap strategy

---

lua/neotest/config/init.lua
lua/neotest/consumers/watch/watcher.lua

- Add queries for Haskell
- Add queries for Rust
- Fix an error that is thrown if no definitions are found for a set of queries

feat(watcher): symbol queries for haskell and rust

---

lua/neotest/config/init.lua
lua/neotest/consumers/summary/component.lua

Adds a binding (default `?`) to the summary panel that shows the list of key mappings.
Fixes #230
I'm not very familiar with lua and neovim plugin dev so this might not be the best way to implement it. The mappings are just shown as text and it's not very readable but I don't know how to format the text to make it look better.

Add help key to summary panel to show mappings

---

lua/neotest/lib/file/init.lua

When a respository is in a symlink-ed path (eg: larger hard-drive for projects w/ small SDD for OS), calling `nio.uv.fs_realpath` will perform symlink resolution. https://github.com/nvim-neotest/neotest/blob/f6048f32be831907fb15018af2688ff6633704fc/lua/neotest/lib/file/init.lua#L233
Given the following scenario, nvim will run buffers with the home-dir path, instead of the resolved symlink path.
```sh
ln -s $HOME/projects /mnt/largehdd/projets
cd $HOME/projects/my_project
nvim .
```
Then, the following lua code will result on 2 different filenames.
```lua
local path_name = vim.api.nvim_buf_get_name(0) -- /home/me/projects/my_project/src/lib.rs
neotest.lib.files.path.real(path_name) -- /mnt/largehdd/projects/my_project/src/lib.rs
```
When sending the fully resolved symlinked path to a …

fix(find): Use full path instead of real path to avoid symlinks

---

lua/neotest/consumers/watch/init.lua
lua/neotest/consumers/watch/watcher.lua

This is useful e.g. for checking if the buffer has any error diagnostics from the LSP client, in which case one would probably not want to rerun the tests yet.

feat(watch): allow passing in `run_predicate` that takes a bufnr

---

lua/neotest/client/init.lua

Problem: Warning messages via `vim.notify` do not retain stack trace,
which makes errors or bugs happened on the adapters' side difficult
to troubleshoot. E.g.:
```
neotest-python: vim/_editor.lua:0: E5560: Vimscript function must not be called in a lua loop callback
```
Solution: Use `xpcall`, instead of `pcall` to access the stacktrace
information, and use it when showing warning (error) messages. E.g.:

feat(client): show stacktrace information when adapter fails

---

lua/neotest/consumers/diagnostic.lua

I'm writing my own neotest adapter and I'm sending in error messages along with line numbers:
```lua
---@type string
local matched_line_number = string.match(line.Output, test_filename .. ":(%d+)")
---@type number | nil
local line_number = tonumber(matched_line_number)
if line_number ~= nil then
---@type neotest.Error
error = { message = line.Output, line = line_number }
else
---@type neotest.Error
error = { message = line.Output }
end
```
Full source [here](https://github.com/fredrikaverpil/neotest-golang/blob/main/lua/neotest-golang/init.lua).
Sometimes, and only when a line number (an integer) is sent in, I see this crash in Neovim, and neotest breaks:
```
  Error  15:32:53 msg_show.lua_error Error executing vim.schedule lua callback: …
```

fix: avoid arithmetic error (subtracting 1 from nil)

---

lua/neotest/consumers/diagnostic.lua

The error happens when deleting the buffer.

fix: check buffer valid before set diagnostic

---

README.md

StencilJS is a frontend framework for creating web components, similar to Lit. It has a builtin test runner that uses Jest and Puppeteer under the hood.  Credit goes to neotest-jest, which provided a great starting point for neotest-stenciljs!
adapter: https://github.com/benelan/neotest-stenciljs
stencil: https://github.com/ionic-team/stencil
ref: https://stenciljs.com/docs/testing/stencil-testrunner/overview

docs(readme): add StencilJS adapter to list

---

lua/neotest/lib/file/init.lua
lua/neotest/lib/positions/init.lua
lua/neotest/logging.lua
lua/neotest/utils/init.lua
scripts/gendocs.lua

fix: replace tbl_flatten to flatten():totable()

---

lua/neotest/client/init.lua

I encountered a bunch of error in Neotest when I started Neovim in verbose mode (`nvim -V1`), coming from these autocmds. Turns out, when `expand()` fails in verbose mode it will throw an error instead of expanding to the empty string (see https://github.com/neovim/neovim/issues/29175). You can reproduce the issue using the minimal init file below:
```lua
-- save as repro.lua
-- run with nvim -V1 -u repro.lua
local root = vim.fn.fnamemodify("./.repro", ":p")
-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end
vim.g.mapleader = " "
-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
vim.fn.system({
"git",
"clone", …
```

fix: no autocommand file name to substitute for <afile>

---

lua/neotest/consumers/status.lua
lua/neotest/lib/ui/init.lua

I'm occasionally getting an `Invalid 'line': out of range`, probably because buffer changed and the line is not there.
Also if I don't open the test in a buffer - it errors despite the existing check (any help understanding why is appreciated).

safer place_sign

---

README.md

neodev.nvim is now end of life and users are encouraged to migrate to lazydev.nvim.
Fixes https://github.com/nvim-neotest/neotest/issues/417

Replace link to neodev.nvim with link to lazydev.nvim

---

README.md

I've made another adapter for Go, in [`fredrikaverpil/neotest-golang`](https://github.com/fredrikaverpil/neotest-golang), as I was having a lot of issues with the one listed in the README. My adapter outlines those problems [here](https://github.com/fredrikaverpil/neotest-golang#neotest-go-issues-mitigated-in-neotest-golang).
I figured it could be helpful for others to list my adapter as an alternative, for others who might also have issues with the currently listed Go adapter. 😄

Add neotest-golang to README

---

lua/neotest/lib/window.lua

Adds an additional check to the self.buffer function of PersistedWindow to see if the current bufnr still exists. This prevents a crash in cases where the persisted window's buffer has been deleted by an external script.
Fixes N/A

fix(window): handle when a PersistedWindow's buffer has been deleted

---

lua/neotest/client/strategies/init.lua
lua/neotest/config/init.lua

On Android devices, the function `vim.loop.cpu_info()` returns a nil value, since it is unable to read from `/proc` for security reasons. We should handle that failure properly in Neotest and avoid panicking.

fix: properly handle nil value from cpu_info()

---

lua/neotest/lib/window.lua

this is now deprecated in 0.10 and can be replaced with nvim_set_option_value
per https://neovim.io/doc/user/deprecated.html#deprecated-0.10
Fixes: N/A

chore(window): replace deprecated usage nvim_buf_set_option

---

doc/neotest.txt
lua/neotest/config/init.lua
lua/neotest/consumers/run.lua

Allow users to augment the arguments to all tests being run from a singular function.
```lua
local nio = require("nio")
neotest.setup({
run = {
augment = function(tree, args)
local name = nio.ui.input({ prompt = "What is your name?" })
args.env = { USER_NAME = name }
return args
end,
},
})
```
See #431

feat(run): augment args

---

lua/neotest/lib/process/init.lua

This issue manifested itself it a weird way. While testing an adapter, I noticed that the process I was running to list tests via the underlying test runner would stall if there were too many tests being run. If I commented out some tests the process suddenly finished fine without stalling. If it stalled, I could kill the process and the adapter would start responding again. Subsequent runs would yield "No tests found".
I believe the issue is related to I/O buffering of stdout/stderr and the fact that the process is waited on immediately after spawning it.
Consider a case where the output to stderr fits within the buffer:
1. Spawn process.
2. Wait for process to finish.
3. Process outputs to stderr then finishes.
4. `exit_future.set` is called.
5. stderr is read via `read_start`.
Then …

Fix `lib.process.run` stall

---

lua/neotest/client/init.lua

fix: ignore unnamed buffers on autocmd

---

lua/neotest/config/init.lua
lua/neotest/lib/treesitter/init.lua

After https://github.com/neovim/neovim/commit/6913c5e1d975a11262d08b3339d50b579e6b6bb8 in Neovim nightly, neotest returns `No tests found` (tested with `neotest-python`). Since it's mentioned in the PR that the option `all = false` will be removed in the future, maybe a more robust approach would be preferable, but I don't have the knowledge to implement it. This is just a hotfix until someone else comes with something better.

fix(query): explicitly opt-in to legacy behavior

---

lua/neotest/consumers/watch/init.lua

Fixes #425.
For reference: https://github.com/neovim/neovim/commit/ddd92a70d2aab5247895e89abaaa79c62ba7dbb4.

feat: use client.supports_method instead of client.server_capabilities

---

lua/neotest/consumers/watch/init.lua

On the version v0.10.1, supports_method is still a table, rather than a function. Trying to access the table field as a function resulted in following error:
```
attempt to call field 'supports_method' (a table value)
```
This behavior is now fixed.

Fix: Test watch won't start on v0.10.1

---

lua/neotest/config/init.lua
lua/neotest/lib/treesitter/init.lua

https://github.com/nvim-neotest/neotest/pull/450 sometimes breaks test parsing behavior after changing directories, because we're passing `_` instead of a `nil` value to the `iter_matches` function.
This PR fixes the problem.

fix(query): use `nil` to skip optional parameters when calling the iter_matches method

---

lua/neotest/consumers/watch/init.lua
lua/neotest/consumers/watch/watcher.lua

When watching a spec and editing it at the same time, threre are 2 BufWritePost events triggered on file save. One to update NeotestClientState:update_positions and the other for the watcher, which runs the spec.
If the watcher spec is run before the positions are updated, it is run with the stale tree and there is a mismatch in positions ids.
To fix this: I added a wait for an discover_positions event.

fix(watcher): race condition between positions update and watch run on BufWritePost

---

lua/neotest/consumers/output_panel/init.lua
lua/neotest/lib/window.lua
tests/unit/consumers/output_panel_spec.lua

A fix for 2 issues that appear if `output_panel` is closed by the user manually and not with `output_pannel.toggle/close()`:
1.  The buffer id for output panel becomes invalid, so there is an error when trying to open the panel again.  Currently the check with `vim.fn.bufexists()` does not catch buffers that exist, but are unloaded.  Fix - recreate the buffer.
2.  The channel id for term bound to panel buffer becomes invalid, so there is an error when trying to write to that channel.  Fix - recreate the term.
Also, a fix with associated issue: if you reaload the plugin with say `Lazy reload neotest`, the old panel buffer still exists, so when a new buffer is created with the same name, there is an error of trying to rename existing buffer.  Fix - delete buffer with the same name, when …

fix(output_panel): recreate window and term channel if panel closed manually

---

lua/neotest/consumers/status.lua

fix(ui): combine virtual text bg highlight with cursor line bg

---

lua/neotest/consumers/quickfix.lua

This update introduces the triggering of the QuickFixCmdPost event after the quickfix list is set.
The primary purpose of this change is to ensure tools like Trouble can update properly, especially in scenarios where there are no failing tests remaining.

feat: triggering QuickFixCmdPost event after setting quickfix list

---

doc/neotest.txt
lua/neotest/consumers/init.lua

Updated docs to point to https://github.com/folke/lazydev.nvim.

docs: add link to lazydev.nvim for hints/docs

---

lua/neotest/consumers/watch/watcher.lua

#479 introduced a small bug where the watcher would wait for the ```discover_positions_event``` by the listener set up by the init function. This PR fixes it by checking if the changed file is relevant to the discover_position_event.

fix: watcher unnecessarily waiting for discover position event to be set

---

lua/neotest/config/init.lua

tree-sitter-haskell has undergone a rewrite:
- https://github.com/tree-sitter/tree-sitter-haskell/pull/120
This PR updates the `watch` query for Haskell.

fix(watch): update Haskell query

---

README.md

I made an adapter for the bun test runner (https://bun.sh/docs/cli/test), and thought it might be useful for others as well

Add neotest-bun to docs

---

README.md

Adds an alternative adapter for dotnet which uses the vstest runner

docs(README): add neotest-vstest

---

lua/neotest/consumers/quickfix.lua

Currently when you run a test and you've enabled the `quickfix` consumer in your config, it will populate the quickfix list as you would expect. However if you run a test and it passes, it will still populate the quickfix list with an empty list. It makes sense to not override the quickfix list if no errors were raised from the test run.

fix: only populate quickfix if we have errors

---

lua/neotest/lib/treesitter/init.lua
tests/unit/lib/treesitter/init_spec.lua

Closes #516 
My specific use case is to allow for appending/prepending text to `@test.name` and `@namespace.name` for [neotest-kotlin](https://github.com/codymikol/neotest-kotlin) where the testing frameworks we're trying to support append text to namespace and test names. See the issue for a complete example!
This is a non-breaking change, as it passes a new arg to `build_position` of TSMetadata which in my personal use case I'll only be using `text` from.
Here's my expected implementation using this new feature
```lua
local function get_match_type(captured_nodes)
if captured_nodes["test.name"] then
return "test"
end
if captured_nodes["namespace.name"] then
return "namespace"
end
end
local function build_position(file_path, source, captured_nodes, metadata)
local match_type = …
```

feat: build_position provide treesitter node metadata

---

.github/workflows/workflow.yaml

the artifacts used to have the name linux64, but were split into x86_64 and arm64. This should make the nightly builds run successfully.
Fixes: #515

build: use correct targets for neovim builds.

---

doc/neotest.txt
lua/neotest/config/init.lua

Problem: winborder is not respected because border is hardcoded to "rounded".
Solution: default to nil which will use winborder if set by the user.
Minor drawback: winborder was added in 0.11, and for users on a version less than this which was just using a default options, they now need to set it. I feel like this is reasonable though, and not assume which border the users want

fix(border): default border to nil to respect winborder

---

tests/unit/client/strategies/integrated_spec.lua

This commit reduces the flakiness of some tests that rely on timing when executed as part of a nix-build.

fix(test): reduce test flakiness
