nvim-neotest/neotest

- lua/neotest/logging.lua
The current logger is unable to change the logging level
The class structure did not seem to be set up correctly. Tracing the logic from the existing `require('neotest.logging'):set_level('WARN')`:
1. `require('neotest.logging')` resolves to the result of `Logger:new()`
2. `Logger:new()` effectively returns `setmetatable(logger, Logger)`
3. There is no `__index` field on the Logger metatable, so looking up `set_level` will return nil
The fix is to `setmetatable(logger, { __index = Logger })`, and to also set the `_level` onto the logger object instead of the Logger class. It kind of doesn't matter because they're both effectively singletons, but it's technically more correct? ¯\\_(ツ)_/¯
I also slipped in a call to set the default log location to `stdpath('log')` if available (upcoming in …
> fix: expose ability to set logger level

- lua/neotest/lib/treesitter/init.lua
I stumbled across the approach while fiddling around with the treesitter parsing logic. Currently we're reading a file, splitting it by newline, inserting it into a new buffer, parsing the buffer, then deleting the buffer. If we use a TS string parser instead, we just read the file and parse the contents directly. My very unscientific benchmark of opening the summary in the cpython repo and waiting for results to populate took the search time down from ~10s to ~2s. Seems like a win!
> perf: use treesitter string parser for test discovery

- README.md
Hi, thanks for this great plugin! I wrote an adapter for the testthat package for R.
> Update README with link to testthat adapter

- lua/neotest/consumers/output.lua
> Add check for output field (filename) on results

- doc/neotest.txt
- lua/neotest/adapters/init.lua
- lua/neotest/client/init.lua
- lua/neotest/client/runner.lua
- lua/neotest/client/state/init.lua
- lua/neotest/client/strategies/dap/init.lua
- lua/neotest/config/init.lua
- lua/neotest/consumers/diagnostic.lua
- lua/neotest/consumers/summary/init.lua
- lua/neotest/init.lua
- tests/init.vim
- tests/unit/client/init_spec.lua
- tests/unit/client/state_spec.lua
Allows users to configure settings per-project including test discovery
and adapters.
> feat: project configurations

- lua/neotest/lib/treesitter/init.lua
This allows it to be used by other parts of the code, or plugins, who need to perform a query:
```
local query = "<a treesitter query>"
local content = lib.files.read(path)
local ts_root, lang = lib.treesitter.get_parse_root(path, content, { fast = true })
local built_query = lib.treesitter.normalise_query(lang, query)
local has_match = built_query:iter_matches(ts_root, content)() ~= nil
```
> feat(treesitter): refactor generic querying to separate functions

- README.md
Simple change to the README to list an adapter for [PestPHP](https://pestphp.com).
> Add adapter for Pest (PHP)

- README.md
Adds [neotest-minitest](https://github.com/zidhuss/neotest-minitest) to the README.
> docs(README): add neotest-minitest

- lua/neotest/config/init.lua
This should capture most of the types, functions, vars and constants that can be affected by change. I tested it on my own corpus for a while and am super happy with the result! Thank you for this awesome feature!!
> Add watcher support for Go

- README.md
Hey 👋🏾 
I don't know what your requirements are for listed runners in terms of support and maintenance. But in case you are fine with it, I added a link to my Gradle runner I just exported from my NeoVim configuration files. Maybe it is helpful to someone. 🤷🏾 🙂 
Feel free to just close the PR if you don't like it.
Thanks for this amazing plugin 🙏🏾
> Add reference to Gradle runner

- README.md
> add neotest-hardhat to README.md

- README.md
rustaceanvim now has a neotest adapter :smile:
> docs(README): add rustaceanvim

- README.md
theutz marked his repo as read-only on Feb. 16, 2024.  V13Axel has taken over development and is continuing to build on it.
> Update supported runners to use new pest fork

- lua/neotest/config/init.lua
This PR enable the watch mode for javascript, typescript and tsx filetype
> :feat add js watcher query

- lua/nio/tests.lua
Follow-up to #366, I have picked the second solution because it maintains the existing interface. I have successfully tested this change with busted, but not with Plenary busted because that one does not work for me in general.
> Dynamically bind busted hook functions

- lua/neotest/config/init.lua
This enables the file watcher feature for the Java devs.
> feat: add java symbol query

- README.md
this adds a kotlin test runner
Fixes N/A
> docs: add neotest-kotlin

- README.md
I have started a new adapter to work with Bazel specifically.
Also adjusted the column alignment of kotlin
> README: add neotest-bazel

- lua/neotest/consumers/diagnostic.lua
> fix(diagnostic): check for nil when getting default_line

- lua/neotest/consumers/summary/init.lua
- lua/neotest/consumers/summary/summary.lua
> Summary: follow on open

- lua/neotest/client/init.lua
- lua/neotest/lib/subprocess.lua
- lua/neotest/lib/treesitter/init.lua
> fix(subprocess): load adapters
